version: "3.8"

services:
  db:
    image: postgres:15
    container_name: jihamdol-db
    environment:
      POSTGRES_USER: jihamdol
      POSTGRES_PASSWORD: jihamdol
      POSTGRES_DB: jihamdol
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: jihamdol-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jihamdol
      SPRING_DATASOURCE_USERNAME: jihamdol
      SPRING_DATASOURCE_PASSWORD: jihamdol
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data:
