
spring:
  datasource:
    url: jdbc:postgresql://db.gsmbdibjiuwdqhrdvsfo.supabase.co:5432/postgres?sslmode=require
    username: postgres.gsmbdibjiuwdqhrdvsfo
    password: chikadol123!
    hikari:
      data-source-properties:
        prepareThreshold: 0
  flyway:
    url: jdbc:postgresql://db.gsmbdibjiuwdqhrdvsfo.supabase.co:5432/postgres?sslmode=require
    user: postgres.gsmbdibjiuwdqhrdvsfo
    password: chikadol123!
    schemas: rev
jwt:
  issuer: rev-app
  secret: ${JWT_SECRET:d0c41382-cae7-44c3-a401-77828c270ab3}
  access-ttl-seconds: 900        # 15분
  refresh-ttl-seconds: 1209600   # 14일