global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rev-backend'

scrape_configs:
  - job_name: 'rev-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'rev-backend'
          environment: 'local'

